export type Voice = {
  id: string;
  name: string;
  gender: "Male" | "Female";
  accent: string;
  provider: string;
  audioUrl: string;
};

export const voices: Voice[] = [
  {
    id: "g6xIsTj2HwM6VR4iXFCw",
    name: "Jessica Anne Bogart - Chatty and Friendly",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/yA8yDNUx4dZ4gwL9ztbTpUEIyR12/voices/g6xIsTj2HwM6VR4iXFCw/1Oqk9SesQxUMxopfgLb7.mp3`,
  },
  {
    id: "7YaUDeaStRuoYg3FKsmU",
    name: "Callie - Playful, Inviting and Friendly",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/RoQ49REhB5NqiEoUB9lDP3A85wR2/voices/7YaUDeaStRuoYg3FKsmU/6nO6lZs8v8qlHkQv7gHx.mp3`,
  },
  {
    id: "eaNNqnkhfRYVtX7U7VLj",
    name: "Clara - Emotional, Dramatic and Polished",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/w3xRN48cyufO7sClUhoW8nFhjhp2/voices/eaNNqnkhfRYVtX7U7VLj/9vJHc59fUWenh8FIDl4p.mp3`,
  },
  {
    id: "EIsgvJT3rwoPvRFG6c4n",
    name: "Clara - Natural and Convincing",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/jrR31yoCg2gTrsSiovAhocmGTi93/voices/EIsgvJT3rwoPvRFG6c4n/kC6KH8bRXrCUGSoTeB46.mp3`,
  },
  {
    id: "uYXf8XasLslADfZ2MB4u",
    name: "Hope - Bubbly, Gossipy and Girly",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/sD92HnMHS9WZLXKNTKxmnC8XmJ32/voices/uYXf8XasLslADfZ2MB4u/M0UTfNFigInhz8LMb4DA.mp3`,
  },
  {
    id: "yM93hbw8Qtvdma2wCnJG",
    name: "Ivanna - Young, Versatile and Casual",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/PbKq2iR4OIeherAWi2xD3ELKlfe2/voices/yM93hbw8Qtvdma2wCnJG/oMTlBHMIOuDLwcm7I1vJ.mp3`,
  },
  {
    id: "ZoiZ8fuDWInAcwPXaVeq",
    name: "Josh - Warm, Smooth and Steady",
    gender: "Male",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/FRG9eBYz8ogKLVm7y3tLhgw1gv13/voices/ZoiZ8fuDWInAcwPXaVeq/9EwzECjtvTDxjoH3F7fg.mp3`,
  },
  {
    id: "WLKp2jV6nrS8aMkPPDRO",
    name: "Paul - Australian Professional Presenter",
    gender: "Male",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/custom/voices/WLKp2jV6nrS8aMkPPDRO/eaTiwieru6XA3d8ocVFK.mp3`,
  },
  {
    id: "2BJW5coyhAzSr8STdHbE",
    name: "Edward - Youthful, Confident and Bright",
    gender: "Male",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/custom/voices/2BJW5coyhAzSr8STdHbE/QvGIrnFANFVMVqR1Ng9A.mp3`,
  },
  {
    id: "kdnRe2koJdOK4Ovxn2DI",
    name: "Eryn - Genuine, Friendly and Natural",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/DXCrxxc55DZsEPNKieedZbV9YeB3/voices/kdnRe2koJdOK4Ovxn2DI/PHZPTflbygqpdJbgCqek.mp3`,
  },
  {
    id: "5u41aNhyCU6hXOcjPPv0",
    name: "Carol - Relatable, Real, Likeable Grandma",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/user_0801kdv521s4fe0s61ww7j0apae0/voices/5u41aNhyCU6hXOcjPPv0/uiFOGdNpWUK1TMPqu6iM.mp3`,
  },
  {
    id: "ys3XeJJA4ArWMhRpcX1D",
    name: "Jess",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/2HZcqzZEh4TnlwGwcKBhADheS652/voices/ys3XeJJA4ArWMhRpcX1D/6JG2cEI4neP1U46J3N8Z.mp3`,
  },
  {
    id: "BIvP0GN1cAtSRTxNHnWS",
    name: "Ellen - Serious, Direct and Confident",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/XneWYDMsJGQ7Q0uqR5YiKixJmLn2/voices/BIvP0GN1cAtSRTxNHnWS/ZIkioQ15FEgRXe1XJXoG.mp3`,
  },
  {
    id: "f5HLTX707KIM4SzJYzSz",
    name: "Brad - Welcoming & Casual",
    gender: "Male",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/workspace/b2109416c7514449a5f06540d10f0e73/voices/f5HLTX707KIM4SzJYzSz/2KB5h80Xjq4fqF7fOv2o.mp3`,
  },
  {
    id: "rhKGiHCLeAC5KPBEZiUq",
    name: "Apple - Quirky, Unique and Relatable",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/B8zOEhDSzLTezjOrqpGOXGIktp22/voices/rhKGiHCLeAC5KPBEZiUq/uFqXwR2C1MlPbUziFVu1.mp3`,
  },
  {
    id: "DYkrAHD8iwork3YSUBbs",
    name: "Tom - Conversations & Books",
    gender: "Male",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/noVlXbj17nbMQVNRkHqTIt4DD4y2/voices/DYkrAHD8iwork3YSUBbs/RNF2lthsoCmS2gIzKrsn.mp3`,
  },
  {
    id: "MzqUf1HbJ8UmQ0wUsx2p",
    name: "Katie X - Call Center English Female",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/TBCGBdfm5sahGkhMn2WcXK1i4Ya2/voices/MzqUf1HbJ8UmQ0wUsx2p/t0eGqs22ZknvrpntIlz4.mp3`,
  },
  {
    id: "exsUS4vynmxd379XN4yO",
    name: "Blondie - Conversational",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/Jiwqdh0ZG1Vkz1pgvv0m1N650rF3/voices/exsUS4vynmxd379XN4yO/Z1h09ab4rUV5TK5cFWIL.mp3`,
  },
  {
    id: "zmcVlqmyk3Jpn5AVYcAL",
    name: "Sapphire - Sweet, Youthful, and Clear",
    gender: "Female",
    accent: "American",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/Mm6xsp97MCb7Yo90tIK3YNjd7As2/voices/zmcVlqmyk3Jpn5AVYcAL/nfb2SHMKN3K1WZANX0WO.mp3`,
  },
  //Canadian
  {
    id: "roYauZ4bOLAKvVZTPLre",
    name: "Lena - Engaging and Relatable Mom",
    gender: "Female",
    accent: "Canadian",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/cqzUDhVyMFb7IVDYvD0aldVKQM82/voices/roYauZ4bOLAKvVZTPLre/7C6DN763DTC04rzjLqer.mp3`,
  },
  {
    id: "ljX1ZrXuDIIRVcmiVSyR",
    name: "Michael - Genuine and Approachable",
    gender: "Male",
    accent: "Canadian",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/4VqpzRE1qwbl6CxCkyp0xKHJru82/voices/ljX1ZrXuDIIRVcmiVSyR/fqP9bUd1RI4SKDK5zNUN.mp3`,
  },
  {
    id: "TgnhEILA8UwUqIMi20rp",
    name: "Jenna - Warm, Relatable and Articulate",
    gender: "Female",
    accent: "Canadian",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/user/eFiNAkiBPjPhvrN6QD2zAnlnApt2/voices/TgnhEILA8UwUqIMi20rp/qWh81aKYbMv6xt2Xy6Cf.mp3`,
  },
  {
    id: "PD83mpO50qeXZtiUWeyo",
    name: "Arthur - Composed, Kind and Natural",
    gender: "Male",
    accent: "Canadian",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/workspace/a0c4ea5ccf4d4990bf0c89afa9f84978/voices/PD83mpO50qeXZtiUWeyo/22089c0e-82dc-4dc9-ae5c-568a50550acf.mp3`,
  },
  //Indian
  {
    id: "NaKPQmdr7mMxXuXrNeFC",
    name: "Monika Sogam - Interactive and Modern",
    gender: "Female",
    accent: "Indian",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/NaKPQmdr7mMxXuXrNeFC/M8v3bi216QmXqy9Nk8s2.mp3`,
  },
  {
    id: "A7AUsa1uITCDpK29MG3m",
    name: "Ranbir - Professional and Confident",
    gender: "Male",
    accent: "Indian",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/A7AUsa1uITCDpK29MG3m/qpEW0psvbS9EIqqN2MW3.mp3`,
  },
  {
    id: "gX28yZeQHE9L4d5iYqPy",
    name: "Nikhil - Young and Conversational",
    gender: "Male",
    accent: "Indian",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/gX28yZeQHE9L4d5iYqPy/GyuM2F4KpP7WFjy5bfv6.mp3`,
  },
  {
    id: "aGb0TwKthRLQTPThYRqI",
    name: "Nila - Professional Guide",
    gender: "Female",
    accent: "Indian",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/aGb0TwKthRLQTPThYRqI/PgEG5T0my6ewWpy6dJ3S.mp3`,
  },
  {
    id: "4O1sYUnmtThcBoSBrri7",
    name: "Maya - Friendly and Cheerful",
    gender: "Female",
    accent: "Indian",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/workspace/514d94e9241c48e8b7905375729c436f/voices/4O1sYUnmtThcBoSBrri7/H62OViSeqwMim7rCIDvv.mp3`,
  },
  {
    id: "MwUMLXurEzSN7bIfIdXF",
    name: "Tripti - Calm and Experienced",
    gender: "Female",
    accent: "Indian",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/MwUMLXurEzSN7bIfIdXF/62r1LCi8DlUpfWpOlSMD.mp3`,
  },
  {
    id: "k8ThSUZ5Vij4z9jQQSvZ",
    name: "Simran - Genuine and Sweet",
    gender: "Female",
    accent: "Indian",
    provider: "11labs",
    audioUrl: `https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/k8ThSUZ5Vij4z9jQQSvZ/CnY7TB6AVg2vuXNQeEOg.mp3`,
  },
];
